package votingsystems.utilities;

public enum TestCases {
    THREE_CANDIDATES,
    FOUR_CANDIDATES, 
    FIVE_CANDIDATES, 
    SIX_CANDIDATES,
    TEN_CANDIDATES,
    DISSERTATION_EXAMPLE, 
    INCOMPLETE_BALLOTS,
    TEST_CASE_1,
    TEST_CASE_2,
    TEST_CASE_3,
    TEST_CASE_4,
    TEST_CASE_5,
    TEST_CASE_6,
    RANDOM
}
